WebSocket server settings:
  - Listen on :6080
  - No SSL/TLS support (no cert file)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/zagent/websockify/websockify/__main__.py", line 4, in <module>
    websockify.websocketproxy.websockify_init()
  File "/root/zagent/websockify/websockify/websocketproxy.py", line 726, in websockify_init
    server.start_server()
  File "/root/zagent/websockify/websockify/websockifyserver.py", line 704, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False,
  File "/root/zagent/websockify/websockify/websockifyserver.py", line 470, in socket
    sock.bind(addrs[0][4])
OSError: [Errno 98] Address already in use
